// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_layout from './routes/_layout.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $about from './routes/about.tsx';
import * as $account_middleware from './routes/account/_middleware.ts';
import * as $account_change_password from './routes/account/change-password.tsx';
import * as $account_index from './routes/account/index.tsx';
import * as $api_instances_id_ from './routes/api/instances/[id].ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $api_login from './routes/api/login.ts';
import * as $api_templates_id_ from './routes/api/templates/[id].ts';
import * as $countdown from './routes/countdown.tsx';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $index from './routes/index.tsx';
import * as $instances_id_index from './routes/instances/[id]/index.tsx';
import * as $instances_middleware from './routes/instances/_middleware.ts';
import * as $instances_create from './routes/instances/create.tsx';
import * as $instances_index from './routes/instances/index.tsx';
import * as $login from './routes/login.tsx';
import * as $logout from './routes/logout.ts';
import * as $register from './routes/register.tsx';
import * as $search from './routes/search.tsx';
import * as $templates_id_delete from './routes/templates/[id]/delete.tsx';
import * as $templates_id_edit from './routes/templates/[id]/edit.tsx';
import * as $templates_id_index from './routes/templates/[id]/index.tsx';
import * as $templates_middleware from './routes/templates/_middleware.ts';
import * as $templates_index from './routes/templates/index.tsx';
import * as $templates_new from './routes/templates/new.tsx';
import * as $CountDown from './islands/CountDown.tsx';
import * as $Counter from './islands/Counter.tsx';
import * as $Login from './islands/Login.tsx';
import * as $NavBarUserMenu from './islands/NavBarUserMenu.tsx';
import * as $instances_id_islands_InstanceEditor from './routes/instances/[id]/(_islands)/InstanceEditor.tsx';
import * as $instances_id_islands_InstanceLineItemEditor from './routes/instances/[id]/(_islands)/InstanceLineItemEditor.tsx';
import * as $instances_id_islands_types from './routes/instances/[id]/(_islands)/types.ts';
import * as $templates_id_islands_TemplateEditor from './routes/templates/[id]/(_islands)/TemplateEditor.tsx';
import * as $templates_id_islands_TemplateLineItemAdd from './routes/templates/[id]/(_islands)/TemplateLineItemAdd.tsx';
import * as $templates_id_islands_TemplateLineItemEditor from './routes/templates/[id]/(_islands)/TemplateLineItemEditor.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_layout.tsx': $_layout,
    './routes/_middleware.ts': $_middleware,
    './routes/about.tsx': $about,
    './routes/account/_middleware.ts': $account_middleware,
    './routes/account/change-password.tsx': $account_change_password,
    './routes/account/index.tsx': $account_index,
    './routes/api/instances/[id].ts': $api_instances_id_,
    './routes/api/joke.ts': $api_joke,
    './routes/api/login.ts': $api_login,
    './routes/api/templates/[id].ts': $api_templates_id_,
    './routes/countdown.tsx': $countdown,
    './routes/greet/[name].tsx': $greet_name_,
    './routes/index.tsx': $index,
    './routes/instances/[id]/index.tsx': $instances_id_index,
    './routes/instances/_middleware.ts': $instances_middleware,
    './routes/instances/create.tsx': $instances_create,
    './routes/instances/index.tsx': $instances_index,
    './routes/login.tsx': $login,
    './routes/logout.ts': $logout,
    './routes/register.tsx': $register,
    './routes/search.tsx': $search,
    './routes/templates/[id]/delete.tsx': $templates_id_delete,
    './routes/templates/[id]/edit.tsx': $templates_id_edit,
    './routes/templates/[id]/index.tsx': $templates_id_index,
    './routes/templates/_middleware.ts': $templates_middleware,
    './routes/templates/index.tsx': $templates_index,
    './routes/templates/new.tsx': $templates_new,
  },
  islands: {
    './islands/CountDown.tsx': $CountDown,
    './islands/Counter.tsx': $Counter,
    './islands/Login.tsx': $Login,
    './islands/NavBarUserMenu.tsx': $NavBarUserMenu,
    './routes/instances/[id]/(_islands)/InstanceEditor.tsx':
      $instances_id_islands_InstanceEditor,
    './routes/instances/[id]/(_islands)/InstanceLineItemEditor.tsx':
      $instances_id_islands_InstanceLineItemEditor,
    './routes/instances/[id]/(_islands)/types.ts': $instances_id_islands_types,
    './routes/templates/[id]/(_islands)/TemplateEditor.tsx':
      $templates_id_islands_TemplateEditor,
    './routes/templates/[id]/(_islands)/TemplateLineItemAdd.tsx':
      $templates_id_islands_TemplateLineItemAdd,
    './routes/templates/[id]/(_islands)/TemplateLineItemEditor.tsx':
      $templates_id_islands_TemplateLineItemEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
